version: '3.8'

services:
    django:
        container_name: cleaning_service_django
        build: .
        volumes:
            - .:/app
        ports:
            - "8808:8000"
        env_file:
            - .env
        networks:
            - cleaning_service_network

    postgres:
        container_name: cleaning_service_postgres
        image: postgres:13
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=cleaning_service
            - POSTGRES_USER=cleaning_service
            - POSTGRES_PASSWORD=cleaning_service
        networks:
            - cleaning_service_network

    redis:
        container_name: cleaning_service_redis
        image: redis:6.2-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - cleaning_service_network

    celery_worker:
        container_name: cleaning_service_celery
        build: .
        env_file:
            - .env
        volumes:
            - .:/app
        depends_on:
            - django
            - redis
        command: celery --app config.celery.app worker --loglevel INFO
        networks:
            - cleaning_service_network

networks:
    cleaning_service_network:

volumes:
    postgres_data:
    redis_data:
