# Generated by Django 5.1.6 on 2025-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='filename',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
