# Generated by Django 5.1.6 on 2025-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_filename_alter_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
