# Generated by Django 5.1.6 on 2025-04-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_customer_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='invoices_em_is_empl_fc2a3e_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['code'], name='invoices_em_code_76507a_idx'),
        ),
    ]
