# Generated by Django 5.1.6 on 2025-04-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_delete_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_employer'], name='invoices_em_is_empl_fc2a3e_idx'),
        ),
    ]
