# Generated by Django 5.1.6 on 2025-04-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_employer_remove_invoice_customer_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='invoices_em_is_empl_fc2a3e_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_employer',
        ),
    ]
