# Generated by Django 5.1.6 on 2025-05-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_remove_employee_invoices_em_is_empl_fc2a3e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='hours',
            field=models.FloatField(),
        ),
    ]
