# Generated by Django 5.1.6 on 2025-05-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_customerinvoice_delete_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='number',
        ),
    ]
