# Generated by Django 5.1.6 on 2025-05-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_remove_customerinvoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='google_drive_url',
        ),
    ]
