# Generated by Django 5.1.6 on 2025-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_nr',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='st_nr',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
