# Generated by Django 5.1.6 on 2025-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_employee_id_nr_employee_nip_employee_st_nr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeebankaccount',
            old_name='account_number',
            new_name='iban',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_nr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='st_nr',
        ),
        migrations.AddField(
            model_name='employee',
            name='specifications',
            field=models.JSONField(default=dict),
        ),
    ]
