# Generated by Django 5.1.6 on 2025-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_rename_account_number_employeebankaccount_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=4),
        ),
    ]
