# Generated by Django 5.1.6 on 2025-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_address_bankaccount_remove_employeeaddress_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
