# Generated by Django 5.1.6 on 2025-06-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_customer_metadata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='works_custo_company_a9001b_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
    ]
